apiVersion: scheduling.k8s.io/v1
description: Priority class used by pods critical to rancher's functionality.
globalDefault: false
kind: PriorityClass
metadata:
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-critical
value: 1000000000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui
---
apiVersion: v1
data:
  priorityClassName: rancher-critical
kind: ConfigMap
metadata:
  labels:
    app: rancher-ui
    app.kubernetes.io/part-of: rancher
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: rancher-ui
    namespace: argocd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https-internal
      port: 443
      protocol: TCP
      targetPort: 444
  selector:
    app: rancher-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rancher-ui
        release: rancher-ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: NotIn
                    values:
                      - windows
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rancher-ui
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - --http-listen-port=80
            - --https-listen-port=443
            - --add-local=true
          env:
            - name: CATTLE_NAMESPACE
              value: argocd
            - name: CATTLE_PEER_SERVICE
              value: rancher-ui
            - name: IMPERATIVE_API_DIRECT
              value: "true"
            - name: IMPERATIVE_API_APP_SELECTOR
              value: rancher-ui
          image: docker.io/rancher/rancher:v2.12.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 30
            timeoutSeconds: 5
          name: rancher
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 6666
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 30
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts: null
      priorityClassName: rancher-critical
      serviceAccountName: rancher-ui
      tolerations:
        - effect: NoSchedule
          key: cattle.io/os
          operator: Equal
          value: linux
      volumes: null
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: rancher-ui
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui
spec:
  rules:
    - host: rancher.example.com
      http:
        paths:
          - backend:
              service:
                name: rancher-ui
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - rancher.example.com
      secretName: tls-rancher-ingress
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui
spec:
  ca:
    secretName: tls-rancher
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "1"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-post-delete
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-pre-upgrade
  namespace: argocd
---
apiVersion: v1
data:
  post-delete-hook.sh: |-
    #!/bin/bash

    set -e

    namespaces="${NAMESPACES}"
    rancher_namespace="${RANCHER_NAMESPACE}"
    timeout="${TIMEOUT}"
    ignoreTimeoutError="${IGNORETIMEOUTERROR}"

    if [[ -z ${namespaces} ]]; then
      echo "No namespace is provided."
      exit 1
    fi

    if [[ -z ${rancher_namespace} ]]; then
      echo "No rancher namespace is provided."
      exit 1
    fi

    if [[ -z ${timeout} ]]; then
      echo "No timeout value is provided."
      exit 1
    fi

    if [[ -z ${ignoreTimeoutError} ]]; then
      echo "No ignoreTimeoutError value is provided."
      exit 1
    fi

    succeeded=()
    failed=()

    get_pod_count() {
      kubectl get pods --selector app="${1}" -n "${2}" -o json | jq '.items | length'
    }

    echo "Uninstalling Rancher resources in the following namespaces: ${namespaces}"

    for namespace in ${namespaces}; do
      for app in $(helm list -n "${namespace}" -q); do
        if [[ ${app} =~ .crd$ ]]; then
          echo "--- Skip the app [${app}] in the namespace [${namespace}]"
          continue
        fi
        echo "--- Deleting the app [${app}] in the namespace [${namespace}]"
        if [[ ! $(helm uninstall "${app}" -n "${namespace}") ]]; then
          failed=("${failed[@]}" "${app}")
          continue
        fi

        t=0
        while true; do
          if [[ $(get_pod_count "${app}" "${namespace}") -eq 0 ]]; then
            echo "successfully uninstalled [${app}] in the namespace [${namespace}]"
            succeeded=("${succeeded[@]}" "${app}")
            break
          fi
          if [[ ${t} -ge ${timeout} ]]; then
            echo "timeout uninstalling [${app}] in the namespace [${namespace}]"
            failed=("${failed[@]}" "${app}")
            break
          fi
          # by default, wait 120 seconds in total for an app to be uninstalled
          echo "waiting 5 seconds for pods of [${app}] to be terminated ..."
          sleep 5
          t=$((t + 5))
        done
      done

      # delete the helm operator pods
      for pod in $(kubectl get pods -n "${namespace}" -o name); do
        if [[ ${pod} =~ ^pod\/helm-operation-* ]]; then
          echo "--- Deleting the pod [${pod}] in the namespace [${namespace}]"
          kubectl delete "${pod}" -n "${namespace}"
        fi
      done
    done

    echo "Removing Rancher bootstrap secret in the following namespace: ${rancher_namespace}"
    kubectl --ignore-not-found=true delete secret bootstrap-secret -n "${rancher_namespace}"

    echo "------ Summary ------"
    if [[ ${#succeeded[@]} -ne 0 ]]; then
      echo "Succeeded to uninstall the following apps:" "${succeeded[@]}"
    fi

    if [[ ${#failed[@]} -ne 0 ]]; then
      echo "Failed to uninstall the following apps:" "${failed[@]}"
      if [[ "${ignoreTimeoutError}" == "false" ]]; then
        exit 2
      fi
    else
      echo "Cleanup finished successfully."
    fi
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "1"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-post-delete
  namespace: argocd
---
apiVersion: v1
data:
  pre-upgrade-hook.sh: |-
    #!/bin/bash

    set -eo pipefail

    # Global counters
    declare -A COUNTS
    RESOURCES_FOUND=false

    check_prerequisites() {
      if ! command -v kubectl &>/dev/null; then
        echo "Missing required tool: kubectl"
        exit 1
      fi
    }

    print_resource_table() {
      local kind="$1"
      local items="$2"
      local -a headers=("${@:3}")

      local count
      count=$(wc -l <<< "$items")
      COUNTS["$kind"]=$count
      RESOURCES_FOUND=true

      echo "Found $count $kind resource(s):"
      echo

      IFS=$'\n' read -r -d '' -a lines < <(printf '%s\0' "$items")

      # Initialize max_lengths array with header lengths
      local -a max_lengths
      for i in "${!headers[@]}"; do
        max_lengths[i]=${#headers[i]}
      done

      # Calculate max width for each column
      for line in "${lines[@]}"; do
        IFS=$'\t' read -r -a cols <<< "$line"
        for i in "${!cols[@]}"; do
          (( ${#cols[i]} > max_lengths[i] )) && max_lengths[i]=${#cols[i]}
        done
      done

      for i in "${!headers[@]}"; do
        printf "%-${max_lengths[i]}s  " "${headers[i]}"
      done
      printf "\n"

      for i in "${!headers[@]}"; do
        printf "%-${max_lengths[i]}s  " "$(printf '%*s' "${max_lengths[i]}" '' | tr ' ' '-')"
      done
      printf "\n"

      for line in "${lines[@]}"; do
        IFS=$'\t' read -r -a cols <<< "$line"
        for i in "${!cols[@]}"; do
          printf "%-${max_lengths[i]}s  " "${cols[i]}"
        done
        printf "\n"
      done

      echo
    }

    detect_resource() {
      local crd="$1"
      local kind="$2"
      local jsonpath="$3"
      local -a headers=("${@:4}")

      echo "Checking for $kind resources..."

      local output
      if ! output=$(kubectl get "$crd" --all-namespaces -o=jsonpath="$jsonpath" 2>&1); then
        if grep -q "the server doesn't have a resource type" <<< "$output"; then
          echo "Resource type $crd not found. Skipping."
          echo
          return 0
        else
          echo "Error retrieving $kind resources: $output"
          exit 1
        fi
      fi

      if [ -z "$output" ]; then
        echo "No $kind resources found."
        echo
      else
        print_resource_table "$kind" "$output" "${headers[@]}"
      fi
    }

    print_summary() {
      echo "===== SUMMARY ====="
      local total=0
      for kind in "${!COUNTS[@]}"; do
        local count=${COUNTS[$kind]}
        echo "$kind: $count"
        total=$((total + count))
      done

      echo "Total resources detected: $total"

      if [ "$RESOURCES_FOUND" = true ]; then
        echo "Error: Rancher v2.12+ does not support RKE1.
    Detected RKE1-related resources (listed above).
    Please migrate these clusters to RKE2 or K3s, or delete the related resources.
    More info: https://www.suse.com/c/rke-end-of-life-by-july-2025-replatform-to-rke2-or-k3s"
        exit 1
      else
        echo "No RKE related resources found."
      fi
    }

    main() {
      check_prerequisites

      detect_resource "clusters.management.cattle.io" "RKE Management Cluster" \
        '{range .items[?(@.spec.rancherKubernetesEngineConfig)]}{.metadata.name}{"\t"}{.spec.displayName}{"\n"}{end}' \
        "NAME" "DISPLAY NAME"

      detect_resource "nodetemplates.management.cattle.io" "NodeTemplate" \
        '{range .items[*]}{.metadata.namespace}{"\t"}{.metadata.name}{"\t"}{.spec.displayName}{"\n"}{end}' \
        "NAMESPACE" "NAME" "DISPLAY NAME"

      detect_resource "clustertemplates.management.cattle.io" "ClusterTemplate" \
        '{range .items[*]}{.metadata.namespace}{"\t"}{.metadata.name}{"\t"}{.spec.displayName}{"\n"}{end}' \
        "NAMESPACE" "NAME" "DISPLAY NAME"

      print_summary
    }

    main
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-pre-upgrade
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "1"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-post-delete
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - delete
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - services
      - configmaps
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - delete
      - create
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - delete
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-pre-upgrade
rules:
  - apiGroups:
      - management.cattle.io
    resources:
      - clusters
      - nodetemplates
      - clustertemplates
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "2"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-post-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancher-ui-post-delete
subjects:
  - kind: ServiceAccount
    name: rancher-ui-post-delete
    namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-pre-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancher-ui-pre-upgrade
subjects:
  - kind: ServiceAccount
    name: rancher-ui-pre-upgrade
    namespace: argocd
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "3"
  labels:
    app: rancher-ui
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-post-delete
  namespace: argocd
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: rancher-ui
        chart: rancher-2.12.1
        heritage: Helm
        release: rancher-ui
      name: rancher-ui-post-delete
    spec:
      containers:
        - command:
            - /scripts/post-delete-hook.sh
          env:
            - name: NAMESPACES
              value: cattle-fleet-system cattle-system rancher-operator-system
            - name: RANCHER_NAMESPACE
              value: argocd
            - name: TIMEOUT
              value: "120"
            - name: IGNORETIMEOUTERROR
              value: "false"
          image: rancher/shell:v0.5.0
          imagePullPolicy: IfNotPresent
          name: rancher-post-delete
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /scripts
              name: config-volume
      restartPolicy: OnFailure
      serviceAccountName: rancher-ui-post-delete
      volumes:
        - configMap:
            defaultMode: 511
            name: rancher-ui-post-delete
          name: config-volume
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    app: rancher-ui-pre-upgrade
    chart: rancher-2.12.1
    heritage: Helm
    release: rancher-ui
  name: rancher-ui-pre-upgrade
  namespace: argocd
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: rancher-ui-pre-upgrade
        chart: rancher-2.12.1
        heritage: Helm
        release: rancher-ui
      name: rancher-ui-pre-upgrade
    spec:
      containers:
        - command:
            - /scripts/pre-upgrade-hook.sh
          image: rancher/shell:v0.5.0
          imagePullPolicy: IfNotPresent
          name: rancher-pre-upgrade
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /scripts
              name: config-volume
      restartPolicy: Never
      serviceAccountName: rancher-ui-pre-upgrade
      volumes:
        - configMap:
            defaultMode: 511
            name: rancher-ui-pre-upgrade
          name: config-volume
