apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.9.3
    helm.sh/chart: podinfo-6.9.3
  name: podinfo
  namespace: argocd-e2e
spec:
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 9999
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/name: podinfo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.9.3
    helm.sh/chart: podinfo-6.9.3
  name: podinfo
  namespace: argocd-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9898"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: podinfo
    spec:
      containers:
        - command:
            - ./podinfo
            - --port=9898
            - --cert-path=/data/cert
            - --port-metrics=9797
            - --grpc-port=9999
            - --grpc-service-name=podinfo
            - --level=info
            - --random-delay=false
            - --random-error=false
          env:
            - name: PODINFO_UI_COLOR
              value: '#34577c'
            - name: PODINFO_BACKEND_URL
              value: http://backend-podinfo:9898/echo
          image: ghcr.io/stefanprodan/podinfo:6.9.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/healthz
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: podinfo
          ports:
            - containerPort: 9898
              name: http
              protocol: TCP
            - containerPort: 9797
              name: http-metrics
              protocol: TCP
            - containerPort: 9999
              name: grpc
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/readyz
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 1m
              memory: 16Mi
          volumeMounts:
            - mountPath: /data
              name: data
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: data
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    appmesh.k8s.aws/sidecarInjectorWebhook: disabled
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    linkerd.io/inject: disabled
    sidecar.istio.io/inject: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.9.3
    helm.sh/chart: podinfo-6.9.3
  name: podinfo-grpc-test-sntrh
  namespace: argocd-e2e
spec:
  containers:
    - args:
        - -addr=podinfo.argocd-e2e:9999
      command:
        - grpc_health_probe
      image: stefanprodan/grpc_health_probe:v0.3.0
      name: grpc-health-probe
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    appmesh.k8s.aws/sidecarInjectorWebhook: disabled
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    linkerd.io/inject: disabled
    sidecar.istio.io/inject: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.9.3
    helm.sh/chart: podinfo-6.9.3
  name: podinfo-jwt-test-xnifh
  namespace: argocd-e2e
spec:
  containers:
    - command:
        - sh
        - -c
        - |
          TOKEN=$(curl -sd 'test' ${PODINFO_SVC}/token | jq -r .token) &&
          curl -sH "Authorization: Bearer ${TOKEN}" ${PODINFO_SVC}/token/validate | grep test
      env:
        - name: PODINFO_SVC
          value: podinfo.argocd-e2e:9898
      image: giantswarm/tiny-tools
      name: tools
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    appmesh.k8s.aws/sidecarInjectorWebhook: disabled
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    linkerd.io/inject: disabled
    sidecar.istio.io/inject: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.9.3
    helm.sh/chart: podinfo-6.9.3
  name: podinfo-service-test-llvj5
  namespace: argocd-e2e
spec:
  containers:
    - command:
        - sh
        - -c
        - |
          curl -s ${PODINFO_SVC}/api/info | grep version
      env:
        - name: PODINFO_SVC
          value: podinfo.argocd-e2e:9898
      image: curlimages/curl:7.69.0
      name: curl
  restartPolicy: Never
